--
-- Script generated by Schema Compare for Oracle 5.7.9.293 on 03/11/2020 23:45:27
--
ALTER TABLE hr.employees ADD (ssn VARCHAR2(20 BYTE));

COMMENT ON COLUMN hr.employees.ssn IS 'Social Security number';

