--
-- Script generated by Schema Compare for Oracle 5.7.9.293 on 03/11/2020 06:28:34
--

DROP VIEW hr.emp_details_view;

DROP INDEX hr.dept_location_ix;

DROP TRIGGER hr.update_job_history;

DROP PROCEDURE hr.add_job_history;

DROP INDEX hr.jhist_job_ix;

DROP INDEX hr.jhist_emp_ix;

DROP INDEX hr.jhist_dept_ix;

ALTER TABLE hr.job_history DROP CONSTRAINT jhist_dept_fk;

ALTER TABLE hr.job_history DROP CONSTRAINT jhist_emp_fk;

ALTER TABLE hr.job_history DROP CONSTRAINT jhist_job_fk;

DROP INDEX hr.emp_department_ix;

DROP INDEX hr.emp_job_ix;

DROP INDEX hr.emp_manager_ix;

DROP INDEX hr.emp_name_ix;

ALTER TABLE hr.employees DROP CONSTRAINT emp_dept_fk;

ALTER TABLE hr.employees DROP CONSTRAINT emp_job_fk;

ALTER TABLE hr.employees DROP CONSTRAINT emp_manager_fk;

ALTER TABLE hr.departments DROP CONSTRAINT dept_loc_fk;

ALTER TABLE hr.departments DROP CONSTRAINT dept_mgr_fk;

DROP INDEX hr.loc_city_ix;

DROP INDEX hr.loc_state_prov_ix;

DROP INDEX hr.loc_country_ix;

ALTER TABLE hr.locations DROP CONSTRAINT loc_c_id_fk;

ALTER TABLE hr.countries DROP CONSTRAINT countr_reg_fk;

DROP TABLE hr.regions;

DROP TABLE hr.jobs;

DROP PROCEDURE hr.secure_dml;

DROP TABLE hr.departments;

DROP TABLE hr.employees;

DROP TABLE hr.locations;

DROP TABLE hr.countries;

DROP TABLE hr.job_history;

DROP SEQUENCE hr.locations_seq;

DROP SEQUENCE hr.employees_seq;

DROP SEQUENCE hr.departments_seq;

